var records = [
    "https://edu.gcfglobal.org/en/windowsxp/customizing-windows-xp-using-the-control-panel/1/|Настройка Windows XP|Учебный ресурс GCFGlobal, описывающий настройку через панель управления.",
    "https://www.oreilly.com/library/view/windows-xp-in/0596002491/re66.html|Панель управления XP|Книга от O'Reilly о панели управления как центральном интерфейсе.",
    "https://learn.microsoft.com/en-us/archive/msdn-magazine/2001/november/windows-xp-overview-take-advantage-of-new-windows-xp-features-in-your-apps-today|Новые функции XP|Статья Microsoft о функциях, включая смену пользователей.",
    "https://www.oreilly.com/library/view/windows-xp-home/0596002602/ch09.html|Домашняя версия XP|Глава о панели управления в домашней версии.",
    "https://www.reddit.com/r/windows/comments/rg5sg6/what_useful_features_were_in_windows_xp_7_8_and/|Полезные функции XP|Обсуждение на Reddit о классической панели.",
    "https://en.wikipedia.org/wiki/Control_Panel_%28Windows%29|Панель управления Windows|Википедия о апплетах в XP и Vista.",
    "https://microsoft.fandom.com/wiki/Features_new_to_Windows_XP|Новые функции XP|Фэндом о международной поддержке в панели.",
    "https://news.ycombinator.com/item?id=29586970|Эволюция дизайна|Обсуждение на HN о панели в XP.",
    "https://www.geeksforgeeks.org/techtips/what-is-control-panel/|Что такое Control Panel|Обзор на GeeksforGeeks для XP и Vista.",
    "https://www.youtube.com/watch?v=nPKdNO62fjM|Видеоурок XP|Урок на YouTube о панели в XP.",
    "https://www.oreilly.com/library/view/windows-vista-the/0596528272/ch08.html|Руководство Vista|Глава о панели в Vista.",
    "https://learn.microsoft.com/en-us/windows/win32/uxguide/winenv-ctrl-panels|Документация Vista|О расширяемых элементах в Vista.",
    "https://en.wikipedia.org/wiki/Management_features_new_to_Windows_Vista|Новые функции Vista|Вики о улучшениях панели в Vista.",
    "https://scdltechnologytraining.wordpress.com/2015/03/09/an-introduction-to-the-windows-control-panel/|Введение в Control Panel|Блог о панели как хабе в Vista.",
    "https://support.microsoft.com/en-us/topic/components-of-the-user-interface-in-windows-vista-and-in-windows-server-2008-report-slightly-different-values-for-the-total-physical-memory-that-is-available-on-the-computer-4a285096-5c6f-aded-df26-d2e0f485a7e8|Компоненты UI Vista|Поддержка MS о отчетах в панели Vista.",
    "https://www.lenovo.com/us/en/glossary/windows-vista/?srsltid=AfmBOoojm8nwscakvq4m-ArhXkzCywGa2cNiliRBz2JJSWQGefomMGlL|Глоссарий Vista|Lenovo о функциях Aero и UAC в панели.",
    "https://www.computerhope.com/issues/ch001870.htm|Категории Vista|Описание категорий панели в Vista.",
    "https://www.bleepingcomputer.com/tutorials/windows-vista-feature-guide/|Руководство Vista|Гайд по функциям через панель.",
    "https://www.youtube.com/watch?v=MSK-dmTqI0o|Видео XP|Видео о панели в XP от PCprostoTV.",
    "https://comp5.ru/Teoria/WindowsXP/Windows10-1.php|Настройки XP|Описание основных настроек в XP.",
    "https://www.youtube.com/watch?v=N9-bD3fDq_4|Что такое панель XP|Урок о входе в панель XP.",
    "https://xn----ttbkadddjj.xn--p1ai/xp/panel-upravleniya.html|Обзор XP|Сайт о инструментах панели в XP.",
    "http://phys.bspu.by/static/lib/inf/os/winxp/glava16/index2.htm|Папка панели XP|Учебный материал о панели как специальной папке.",
    "https://studfile.net/preview/7411019/page:11/|Настройка задач XP|Описание элементов панели задач в XP.",
    "http://pcabc.ru/wxp/wxp16.html|Представления XP|О двух видах панели в XP.",
    "https://taurion.ru/windows-xp/1/9|Окна XP|Обзор окон и панели в XP.",
    "https://compress.ru/article.aspx?id=12391|Настройка XP|Статья о индивидуальной настройке через панель.",
    "https://www.youtube.com/watch?v=md9HT9Xnpso|Видео Vista|Урок о панели в Vista.",
    "https://pcabc.ru/wv/wv18.html|Указатели Vista|Описание действий в панели Vista.",
    "http://www.dialektika.com/PDF/978-5-8459-1241-1/part.pdf|Интерфейс Vista|PDF о группировке в панели Vista.",
];